version: '3.8'

services:
  server:
    build: .
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - ./:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - mongo
    container_name: server

  mongo:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    env_file:
      - ./env/mongodb.env
    volumes:
      - mongodb-data:/data/db
    container_name: database

  npm:
    image: thomascode92/docker-util:mynpm
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
    profiles:
      - tools
    container_name: mynpm

volumes:
  mongodb-data:
    name: mongodb-data
    external: true
